---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
      - "my_root_password="
      - "LINK_KEYS_ZIP="

    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/Solana/main/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 32913
        as: 32913
        to:
          - global: true

      - port: 37086
        as: 37086
        to:
          - global: true

      - port: 40233
        as: 40233
        to:
          - global: true

      - port: 41298
        as: 41298
        to:
          - global: true

      - port: 45191
        as: 45191
        to:
          - global: true

      - port: 46444
        as: 46444
        to:
          - global: true

      - port: 49198
        as: 49198
        to:
          - global: true

      - port: 50035
        as: 50035
        to:
          - global: true
	
      - port: 8000
        as: 8000
        to:
          - global: true

      - port: 8899
        as: 8899
        to:
          - global: true
	
      - port: 8001
        as: 8001
        proto: udp
        to:
          - global: true

      - port: 8002
        as: 8002
        proto: udp
        to:
          - global: true

      - port: 8003
        as: 8003
        proto: udp
        to:
          - global: true

      - port: 8004
        as: 8004
        proto: udp
        to:
          - global: true

      - port: 8005
        as: 8005
        proto: udp
        to:
          - global: true

      - port: 8006
        as: 8006
        proto: udp
        to:
          - global: true

      - port: 8007
        as: 8007
        proto: udp
        to:
          - global: true

      - port: 8008
        as: 8008
        proto: udp
        to:
          - global: true
	
      - port: 8009
        as: 8009
        proto: udp
        to:
          - global: true

      - port: 8010
        as: 8010
        proto: udp
        to:
          - global: true
	
      - port: 8011
        as: 8011
        proto: udp
        to:
          - global: true

      - port: 8012
        as: 8012
        proto: udp
        to:
          - global: true

      - port: 8013
        as: 8013
        proto: udp        
        to:
          - global: true
	
      - port: 8014
        as: 8014
        proto: udp
        to:
          - global: true

      - port: 8015
        as: 8015
        proto: udp
        to:
          - global: true
	
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 25.0
        memory:
          size: 16Gi
        storage:
          size: 200Gi

  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 1000000
deployment:
  app:
    akash:
      profile: app
      count: 1
